version: '3.8'

services:
  med-app:
    build: ./
    command: ./scripts/wait-for-postgres.sh db ./med-app
    ports:
      -8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_DB_PASSWORD=12qw#$ER

  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12qw#$ER
      - POSTGRES_USER=postgres
      - POSTGRES_DB=onco_base
    volumes:
      - pgdata:/var/lib/postgresql/data