# Server configurations
server:
  host: "localhost"
  port: 8080

# Database credentials
database:
  host: "localhost"
  port: 5432
  name: "postgres"
  user: "postgres"
  password: ""
  sslmode: "disable"